# Generated by Django 5.0 on 2025-03-03 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='transaction ID')),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount')),
                ('payment_via', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('bank', 'Bank Transfer'), ('card', 'Credit Card')], max_length=20, verbose_name='payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ('-created_at',),
            },
        ),
    ]
