# Generated by Django 5.0 on 2025-02-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='assets/images/user/default-avatar.png', null=True, upload_to='assets/images/user/'),
        ),
    ]
