# Generated by Django 5.0 on 2025-02-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/user/default-avatar.png', null=True, upload_to='images/user/'),
        ),
    ]
