# Generated by Django 5.0 on 2025-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_destination_image_alter_trip_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                default="images/destination/default.jpg",
                upload_to="images/destination/",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="image",
            field=models.ImageField(
                default="images/trip/default.jpg", upload_to="images/trip/"
            ),
        ),
    ]
