# Generated by Django 5.0 on 2025-02-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_favouritedestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='KTM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='location',
            field=models.CharField(default='ktm', max_length=100),
            preserve_default=False,
        ),
    ]
