# Generated by Django 5.0 on 2025-02-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_activities_city_activities_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='facilities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.CharField(default='KTM', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=8000, max_digits=20),
            preserve_default=False,
        ),
    ]
