# Generated by Django 5.0 on 2025-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_package_duration_package_facilities_package_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybooking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activitybooking',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tripbooking',
            name='start_date',
        ),
        migrations.AddField(
            model_name='destination',
            name='travelling_days',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
