# Generated by Django 5.0 on 2025-02-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_activities_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
    ]
