# Generated by Django 5.0 on 2025-02-27 17:09

from django.db import migrations, models
from datetime import date

class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_rename_activities_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitybooking',
            name='start_date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='from_date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='to_date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='start_date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripbooking',
            name='start_date',
            field=models.DateField(default=date.today()),
            preserve_default=False,
        ),
    ]
